version: '3'
services:
  simple-shop:
    build: .
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
networks:
  default:
    driver: bridge
